// <auto-generated />
using System;
using DatabaseWorker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseWorker.Migrations
{
    [DbContext(typeof(VerstaTestTaskContext))]
    [Migration("20220713130327_DeletedDeliveryOrderInfo")]
    partial class DeletedDeliveryOrderInfo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DatabaseWorker.Models.DeletedDeliveryOrderInfo", b =>
                {
                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DeliveryOrderId");

                    b.ToTable("DeletedDeliveryOrderInfo");
                });

            modelBuilder.Entity("DatabaseWorker.Models.DeliveryOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CargoPickupDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("CargoWeight")
                        .HasColumnType("real");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryOrder");
                });

            modelBuilder.Entity("DatabaseWorker.Models.DeletedDeliveryOrderInfo", b =>
                {
                    b.HasOne("DatabaseWorker.Models.DeliveryOrder", "DeliveryOrder")
                        .WithOne("DeletedDeliveryOrderInfo")
                        .HasForeignKey("DatabaseWorker.Models.DeletedDeliveryOrderInfo", "DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryOrder");
                });

            modelBuilder.Entity("DatabaseWorker.Models.DeliveryOrder", b =>
                {
                    b.Navigation("DeletedDeliveryOrderInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
